### PR TITLE
Fix wrong result when using non-equality predicate on idx fields

### LINKED ISSUE #33: Bug bounty Lab 1:  non equality predicates
[Lab 1](https://www.comp.nus.edu.sg/~tankl/cs3223/project/non-equality.htm)

Check if non equality predicates work fine:

- [x] All operators work on string, int
- [x] All operators are present
- [x] Check costing

### PR DESCRIPTION
**Pull request by don-tay**
fixes #33 

## Changes in this PR

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change of an existing feature
- [ ] Refactor/Performance enhancements

## Overview

- Default to a sequential scan when non-equi pred used

### CODE REVIEW

File: src/simpledb/query/Predicate.java [hunk 1]
```diff
@@ -132,17 +132,17 @@ public Predicate joinSubPred(Schema sch1, Schema sch2) {
...
-    * method returns null.
+    * and c is some constant. If so, the method returns that Term (ie. Constant and
+    * Operator). If not, the method returns null.
     * 
     * @param fldname the name of the field
-    * @return either the constant or null
+    * @return either the term or null
     */
-   public Constant equatesWithConstant(String fldname) {
+   public Term equatesWithConstant(String fldname) {
```
Comment (tishyakhanna97) [inline src/simpledb/query/Predicate.java:141]: dont get this change

File: src/simpledb/opt/TablePlanner.java [hunk 2]
```diff
@@ -88,8 +88,10 @@ public Plan makeProductPlan(Plan current) {
 
    private Plan makeIndexSelect() {
       for (String fldname : indexes.keySet()) {
-         Constant val = mypred.equatesWithConstant(fldname);
-         if (val != null) {
+         Term term = mypred.equatesWithConstant(fldname);
```
Comment (tishyakhanna97) [inline src/simpledb/opt/TablePlanner.java:91]: nice

File: src/simpledb/query/Predicate.java (hunk 1 above)
Comment (don-tay) [reply src/simpledb/query/Predicate.java:141]: This is to give access to the operator of the Term (rather than just the constant itself) so that tableplanner can choose to use idx iff the operator is `=`

**Review by xinyee20 — APPROVED** [review]
lgtm
